### ISSUE TITLE
Tickers leak

### ISSUE THREAD

**Issue by funny-falcon** [MEDIGO/go-dlm#3]
https://github.com/MEDIGO/go-dlm/blob/master/redis_dlm.go#L109

**Comment by eggman64** [comment]
Hello! Thanks for opening an issue. Could you describe in more detail the problem you are facing?
Thank you

**Comment by eggman64** [comment]
OK. I did some digging around and saw this 
https://github.com/golang/go/issues/17757
Makes sense. Do you have a proposal for some alternate implementation?

**Comment by funny-falcon** [comment]
It is easy:
```go
	timeout := time.NewTimer(l.waitTime)
	retry := time.NewTicker(l.retryTime)
	defer retry.Stop()

	for {
		select {
		case <-timeout.C:
			return ErrCannotLock
		case <-retry.C:
			ok, err := l.client.SetNX(key, l.token, l.ttl).Result()
			if err != nil {
				timeout.Stop()
				return fmt.Errorf("failed to acquire lock: %v", err)
			}

			if ok {
				l.isHeld = true
				timeout.Stop()
				return nil
			}
		}
	}
```
just never use time.Tick() if you are ain't gonna make infinite loop. And try to not use time.After() if there is a case to not wait until timeout.

**Comment by eggman64** [comment]
Thanks! Would you like to send us a Pull Request? Or shall I use your code?

**Comment by funny-falcon** [comment]
You may use my code.

**Comment by eggman64** [comment]
Thanks @funny-falcon for your help. Closing this issue!
